ElectionFinder/ElectionFinder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('elections/', include('elections.urls')),
    path('admin/', admin.site.urls),
]

ElectionFinder/elections/urls.py
from django.urls import path

from . import views

app_name = 'elections'
urlpatterns = [
    # ex: /elections/
    path('', views.election_form, name='election_form'),
]

ElectionFinder/elections/models.py
from django.db import models

# Create your models here.

ElectionFinder/elections/forms.py
from django import forms

class ElectionForm(forms.Form):
    state = forms.CharField(label='state', max_length=2)
    city = forms.CharField(label='city', max_length=50)

ElectionFinder/elections/views.py
from django.shortcuts import render
from .utils import create_dw_api
import requests
import json

from .forms import ElectionForm

# Create your views here.

def election_form(request):
    if request.method == 'POST':
        form = ElectionForm(request.POST)
        if form.is_valid():
            address = form.cleaned_data
            state = address['state'].strip().lower()
            place = address['city'].strip().replace(" ", "_").lower()

            r = requests.get(create_dw_api(state, place),headers={'Accept': 'application/json' })
            if r.status_code == 200:
                r_text = r.text
                r_jsonify = json.loads(r_text)

                if r_jsonify:
                    r_dict = r_jsonify[0]

                    context = {
                        'state': state,
                        'place': place,
                        'message': 'Whoo hooo! There is an election in ',
                        'date': 'Here is the date:',
                        'election_info': r_dict['date'][:10],
                    }
                else:
                    context = {
                    'sorry' : 'Sorry, no upcoming elections in your area',
                }

            else:
                context = {
                    'sorry' : 'Sorry, those are not valid places',
                }
            return render(request, 'elections/result.html', context)
    else:
        form = ElectionForm()

    return render(request, 'elections/index.html', {'form': form})

ElectionFinder/elections/templates/elections/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'elections/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">    
</head>
<body id="body-overrides">
    <div class="container" id="title">
        <div class="jumbotron" id="jumbotron-overrides">
            <a id="Election Finder" href="{% url 'elections:election_form'%}"> Election Finder</a>
        </div>
    </div>
    {% block index %}
    {% endblock %}
</body>

</html>

ElectionFinder/elections/templates/elections/index.html
{% extends "./base.html" %}
{% load static %}

{% block index %}

<div class="container">
    <div class="row" id="address">
        <form action="/elections/" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit">
        </form>
    </div>
</div>

{% endblock %}

ElectionFinder/elections/templates/elections/result.html
{% extends "./base.html" %}

{% load static %}

{% block index %}

<div class="container">
    <div class="row" id="address">
        <h1>{{Message}} {{place}} {{state}}</h1>
        <h1> {{date}} {{election_info}} </h1>
        <h1>{{sorry}}</h1>
    </div>
</div>

{% endblock %}